### ISSUE TITLE
Canvas context attribute `willReadFrequently` must be set in the initial call to `getContext`

### ISSUE THREAD

**Issue by TrevinAvery** [agmmnn/streaming-avatar-playground#1]
The context attributes of a `Canvas` should be set in the first call to `getContext`. Any changes to these attributes via subsequent calls to `getContext` or by modifying the returned object of `ctx.getContextAttributes` may be ignored. As discussed in [this SO post](https://stackoverflow.com/a/74136040/2463800), when the context is first requested, the texture buffer is loaded on either the GPU (`willReadFrequently == false`, default) or the CPU (`willReadFrequently == true`). After it is loaded, the browser doesn't move it.

The [video-wrap](https://github.com/agmmnn/interactive-avatar-playground/blob/0555bfccc6c26d52239fb0a501305d2f7a55fbe1/src/components/video-wrap.tsx#L44) component attempts to modify the context attributes after they have been set.

```js
ctx.getContextAttributes().willReadFrequently = true
```

It should instead set the attributes in [the first call to `getContext`](https://github.com/agmmnn/interactive-avatar-playground/blob/0555bfccc6c26d52239fb0a501305d2f7a55fbe1/src/components/video-wrap.tsx#L40)

```js
const ctx = canvas.getContext('2d', { willReadFrequently: true })
```

**Comment by agmmnn** [comment]
Thanks for the tip!
